name: Delete old runs
on:
  schedule:
    # Run at 00:00 on Sundays
    - cron:  '0 0 * * 0'
  workflow_dispatch:
  
jobs:
  del_runs:
    name: Delete old workflow runs
    permissions:
      actions: write
    runs-on: ubuntu-latest

    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 10
