name: Update megacloud key

on:
  schedule:
    # Run every 10 minutes
    - cron:  '*/10 * * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update keys
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install Image repo
        run: python3 -m pip install --upgrade Pillow

      #- name: Download the obfuscated script
      #  run: curl ${{ matrix.script_url }} --output script.js

      #- name: Deobfuscate script
      #  continue-on-error: true
       # run: synchrony script.js

      - name: Extract key
        run: python3 .github/scripts/extractKey.py key

      - name: Checkout ${{ matrix.branch }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          path: key_repo

      - name: Update key if it differs
        run: |
          cd key_repo
          echo "Old -> $(cat key) || New -> $(cat ../key)"
          if [[ "$(cat key)" != "$(cat ../key)" ]]; then
            cp ../key .
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add key
            git commit --amend -m "chore: Updating key"
            git push --force
          fi
